# Header
menu:
  Home: /
  # My Works: /works
  About: /about
  # Tags: /tags

rss: /atom.xml

# User Info
user_name: Di&Pan
user_avatar: https://cdn2.iconfinder.com/data/icons/rcons-user/32/male-shadow-circle-512.png
user_location: Earth
user_description: "两只自以为特立独行的猪"
user_contact: xpandi@qq.com
user_introduction: "两只自以为特立独行的猪"

github_username: xpandi-top
twitter_username: 
weibo_username:
zhihu_username: 
facebook_username:
linkedin_username:

# Content
excerpt_link: Read More
fancybox: true

# display widgets at the bottom of index pages (pagination == 2)
#index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
#archive_type: 'monthly'
#show_count: false

# 评论系统
# 不要用别人的 uid, 自己去注册一个吧
use_livere: false
livere_uid: MTAyMC8yOTE4Ni81NzUz

use_disqus: false
disqus_url: https://haojen.disqus.com/embed.js

# Miscellaneous
google_analytics:
favicon: /favicon.png
#twitter:
#google_plus:
#fb_admins:
#fb_app_id:


